import z from 'zod'

export const envSchema = z.object({
  REACT_APP_FIREBASE_API_KEY: z.string(),
  REACT_APP_FIREBASE_AUTH_DOMAIN: z.string(),
  REACT_APP_FIREBASE_PROJECT_ID: z.string(),
  REACT_APP_FIREBASE_STORAGE_BUCKET: z.string(),
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: z.string(),
  REACT_APP_FIREBASE_APP_ID: z.string(),
})

export const envClientSchema = envSchema.parse({
  REACT_APP_FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
  REACT_APP_FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  REACT_APP_FIREBASE_APP_ID: process.env.REACT_APP_FIREBASE_APP_ID,
})
